[package]
name = "ast-resolver-core"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
logos = "0.15.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"] }
